### ISSUE TITLE
create CoRA account for Mike Kenyhercz

### ISSUE THREAD

**Issue by SachinPawaskarUNO** [spawaskar-cora/cora-docs#110]
create CoRA account for Mike Kenyhercz

**Comment by clegarde** [comment]
@mkenyhercz, You should have access after a new release gets pushed this weekend. Please try next week and close and/or comment on this issue accordingly.

**Comment by SachinPawaskarUNO** [comment]
@mkenyhercz, @clegarde This issue has been addressed with a new release. Please verify and close issue if verified.

**Comment by mkenyhercz** [comment]
I just attempted to login - username michael.w.kenyhercz.ctr@mail.mil and
password Peacemaker!2 and still do not have access to CoRA. I tried to also
click on the password reset and received "These credentials do not match
our records".

**Comment by SachinPawaskarUNO** [comment]
@mkenyhercz I just tried login using your credentials and it seems to be working fine. So, I would like you to give me a step by step flow with screenshot of what you are doing and seeing.

**Comment by mkenyhercz** [comment]
I go to the CoRA webpage (http://cora-dev.herokuapp.com), then to the login
page (http://cora-dev.herokuapp.com/login), put in my email (
michael.w.kenyhercz.ctr@mail.mil) and password Peacemaker!2 and get the
following error (screen shot)

**Comment by SachinPawaskarUNO** [comment]
@clegarde, @emilystreetman, can one of you please show @mkenyhercz and @tedunn how to attach a screen shot to GitHub issues.

**Comment by mkenyhercz** [comment]
![cora_login](https://user-images.githubusercontent.com/18051508/38833301-a9c38a96-41b4-11e8-9c91-ace978718df3.JPG)

**Comment by SachinPawaskarUNO** [comment]
@clegarde @emilystreetman @mkenyhercz Wait a second, I just noticed from previous comment that Mike is not going to the correct URL. He is going to the DEV environment instead of CAT. Everyone should be going to [CoRA-CAT](https://cora-dev.herokuapp.com) and using HTTPS instead of HTTP.

@fedamann Please ensure that all DPAA folks are using the correct URLs

**Comment by tedunn** [comment]
Issue resolved for me.

**Comment by mkenyhercz** [comment]
Same, thought he link you provided still took me to the cora-dev. I
switched it to cora-cat and issue is resolved.
