### ISSUE TITLE
Error when doing a DNA search

### ISSUE THREAD

**Issue by clegarde** [spawaskar-cora/cora-docs#150]
DNA > Search. I typed in "154" and then hit enter. Without choosing a "search by" category. I had previously done a mito sequence search, so I thought it would do the same type without choosing. Can this provide error messages like when doing a skeletal element search? (Using Safari on my Mac)

![screen shot 2018-05-08 at 9 24 54 pm](https://user-images.githubusercontent.com/7350474/39792501-969b04e0-5306-11e8-8ab0-9611742ca16e.png)

**Comment by SachinPawaskarUNO** [comment]
@clegarde This issue has been addressed with a new release. Please verify and close issue if verified.

**Comment by clegarde** [comment]
This is still an issue. It looks like for any search under DNA. If you type something in and hit enter (rather than choosing "By Mito Sequence Number"), you get the "Whoops, looks like something went wrong" message, rather than a message like the one below. 
![screen shot 2018-05-30 at 8 38 48 pm](https://user-images.githubusercontent.com/7350474/40756489-82514d88-6449-11e8-8fec-c38b55c97dcd.png)

It is working to search by the same parameter (like Mito Seq #) after I have already selected that once.

**Comment by fedamann** [comment]
@clegarde have a second or third look at this and see if it is still an issue.  Look in https://cora-cat.herokuapp.com/

**Comment by clegarde** [comment]
GTG. With the change of the search, this is no longer an issue. I do get the following error when clicking on the sample number, but I'm assuming this is because the DNA page has not been built out. So closing ticket.
![error clicking on sample number from dna sample search](https://user-images.githubusercontent.com/7350474/45827243-a2bcf980-bcbb-11e8-90bd-0453a0edf040.png)
