### ISSUE TITLE
Server error 500

### ISSUE THREAD

**Issue by Mirkomattia** [spawaskar-cora/cora-docs#659]
Dear sachin,
these days we can't work on CORA: if we open a page other than the dashbord, we come across the error 500 (server error). Can we correct or fix it somehow?
Thanks in advance

**Screenshots**
![screencora](https://user-images.githubusercontent.com/58694974/123936100-28098880-d995-11eb-8226-71c64f041818.jpg)

**Desktop (please complete the following information):**
 - OS: Win 10
 - Browser Chrome and Firefox

**Comment by SachinPawaskarUNO** [comment]
@Mirkomattia @cristinacattaneo @mcummaudo, @deboramazzarelli @andreapalamenghi @LucieBiehlerGomez  This is definitely a bug. Thank you for bringing this to my attention. There was a CoRA upgrade done work the weekend which introduced this. I have fixed this issue. Please verify that this is has been fixed and close the issue if verified as fixed.

**Comment by SachinPawaskarUNO** [comment]
@Mirkomattia @mcummaudo Can you please verify that this is has been fixed and close the issue if verified as fixed.

**Comment by Mirkomattia** [comment]
@SachinPawaskarUNO the pages for the anthropological study now work! Thank you!
But I still get the 500 error if I try, for example, to change my password.

**Comment by SachinPawaskarUNO** [comment]
@Mirkomattia I'm glad the main functionality is now working. Please go ahead and close this ticket and open a new one specifically for the password change functionality.

**Comment by Mirkomattia** [comment]
Thank you Sachin
